title: Veeshan Rayamajhee
email: veeshan@rayamajhee.com
description: >
    Veeshan Rayamajhee's personal website.
url: "http://veeshan.rayamajhee.com"
username: vrayamajhee

#google-analytics: UA-XXXXXXXXX-X

# Build settings
markdown: kramdown
