title: Veeshan Rayamajhee
email: veeshan@rayamajhee.com
description: >
    Veeshan Rayamajhee is a recent UNM graduate with a Ph.D in economics.
url: "http://veeshan.rayamajhee.com"
username: vrayamajhee

# Build settings
markdown: kramdown
