title: Veeshan Rayamajhee
email: veeshan@rayamajhee.com
description: >
    Veeshan Rayamajhee's personal website.
url: "http://veeshan.rayamajhee.com"
username: vrayamajhee


google-analytics: UA-40525098-1

# Build settings
markdown: kramdown
